### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by DandyDev** [ProjectMeniscus/pywebhdfs#19]
I see some open pull requests with no replies/follow-ups, which have been open for quite some time. I like this library, but I'm missing some stuff that is possible with the WebHDFS API, but not in this library. I could contribute, but I don't feel like putting time in it, if PRs are being ignored.

So what's the status of this project?

**Comment by tarnfeld** [comment]
I can't say much about whether @stevendgonzales is still managing the github repository - but we're using this library heavily. I'd be happy to help out reviewing / testing pull requests for the owner of the repo if that would help get things moving... ?

**Comment by chadlung** [comment]
I know Steven the author of this library. In fact, I'll be talking to him tomorrow (Sunday) and I'll mention to him about moving this repo (he has talked to me regarding this a few times). Originally it was setup when we both worked at Rackspace. It would probably make sense now to move it somewhere else where Steven has better control of the repo.

**Comment by DandyDev** [comment]
Thanks for the replies! As soon as I know that work on this repo will be picked up again, I'll send in a PR of my own, to add some missing features (mostly permission management)

**Comment by chadlung** [comment]
The new repo will be located at: https://github.com/pywebhdfs/pywebhdfs
We will start getting things organized over the next few days.

**Comment by chadlung** [comment]
Domain name setup (may take a while to propagate). http://pywebhdfs.org/

**Comment by DandyDev** [comment]
Good looking website :+1: And thanks that you got this going again @chadlung! Will look at how I can contribute :)

**Comment by stevendgonzales** [comment]
thanks @chadlung for setting this up!

**Comment by DandyDev** [comment]
As far as I'm concerned, we can close this now :)

**Comment by laserson** [comment]
If pywebhdfs/pywebhdfs will be the main location for development, can you switch it to be the primary repo and not the fork?  If it's not possible through the admin tools, I think you can contact github to do it for you.

**Comment by chadlung** [comment]
We are trying, we don't have control over the repo anymore.

**Comment by laserson** [comment]
ah, didn't realize that...thanks!

**Comment by DandyDev** [comment]
+1 to Uri's idea. Maybe this is a dumb suggestion: can't you just clone the repo, incl all branches and tags, recreate pywebhdfs/pywebhdfs "standalone" on GH, and push all branches and tags? 
And put a link to the old repo in the README as a courtesy.

**Comment by laserson** [comment]
Yes, that should definitely work.
